# workflow name
name: release

# on events
on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: Navigate in src dir
        run: cd ./src/
      - name: Install dependencies
        run: go install
      - name: Build
        run: go build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Compiled executable
          path: ./src/main
